env:
  browser: true
  es2021: true
extends:
  - airbnb
  - "plugin:@next/next/recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
globals: { "React": "readonly" }
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  {
    "dot-notation": off,
    "react/prop-types": off,
    "react/require-default-props": off,
    "react/require-default-prop": off,
    "react/react-in-jsx-scope": off,
    "react/jsx-filename-extension": off,
    "react/jsx-curly-brace-presence": off,
    "react/jsx-props-no-spreading": off,
    "import/no-unresolved": off,
    "import/extensions": off,
  }
