pet-project:
  component: "@sls-next/serverless-component@1.17.0"
  inputs:
    policy: "arn:aws:iam::031622286897:policy/amatyas-pet-s3-access"
    bucketName: amatyas-pet-project
    cloudfront:
      distributionId: EFJNDJM8NYLQB
  plugins: serverless-s3-remover
  custom:
    remover:
      buckets: amatyas-pet-project
